# Generated by Django 2.0.4 on 2018-04-29 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author_name', models.CharField(default=False, max_length=100)),
                ('publisher', models.CharField(max_length=250)),
                ('ISBN', models.CharField(max_length=100)),
                ('pub_date', models.DateField(default='1900-01-01', verbose_name='published date')),
                ('read_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='date I started')),
                ('read_end_date', models.DateField(default=None, verbose_name='date I finished')),
                ('user_rating', models.IntegerField()),
                ('user_review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_num', models.IntegerField()),
                ('excerpt', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.Book')),
            ],
        ),
    ]
