# Generated by Django 2.0.4 on 2018-05-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ISBN',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn10',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='thumb_url',
            field=models.CharField(default=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='note',
            name='marginalia',
            field=models.TextField(default=False),
        ),
    ]
